Models/ErrorViewModel.cs
namespace asp.net101project.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/products.cs
namespace asp.net101project.Models
{
    public class products
    {
        public int Id { get; set; }
        public string productName { get; set; }
        //public string productDescription { get; set; }
        public int price { get; set; }
        public string productImg { get; set; }
    }
}

Controllers/HomeController.cs
using asp.net101project.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace asp.net101project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/productsController.cs
using asp.net101project.Models;
using Microsoft.AspNetCore.Mvc;

namespace asp.net101project.Controllers
{
    public class productsController : Controller
    {
        public IActionResult Index()
        {
            List<products> products1= new List<products>();
            products1.Add(new products() { Id=0,productName = "Pen", productImg= "pen.jpg",price=9}) ;
            products1.Add(new products() { Id=1, productName = "Book", productImg = "book.jpg", price = 100 });
            ViewData["product"] = products1;
            
            return View(products1);
            //return View();
        }
        public IActionResult Details(int Id)
        {
            
            products product= new products() { Id=3, productName="pencil",
            price=9
            };

            if (Id == product.Id) { ViewData["newProduct"] = product; }
            
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <a class="display-6 text-dark" asp-area="" asp-controller="products" asp-action="Index">Click here to view Products</a>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - asp.net101project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/asp.net101project.styles.css" asp-append-version="true" />
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.NET 101 Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <div class="clear"></div>
    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; 1443 - ASP.NET 101 Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/products/Details.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    var data = (products)ViewData["newProduct"];
}
<p>new product : @data.productName</p>
<p>price : @data.price</p>
    <p class="d-inline">image : @{if (data.productImg == null) {<div class="d-inline">no image </div>}

        else
        {
            <p class="d-inline"><img src ="~/img/@data.productImg" width=50px /></p>
        }}
    </p>

Views/products/Index.cshtml
<h2 class="col-md-4 mt-4 mb-4">Style 1</h2>
<div>
    @{
        var names =(List<products>) ViewData["product"];

        <div class="card-group" style="width: 30rem;">
            @foreach(var c in names)
            {
            <div class="card primary">
              
              <img class="img card-img-top p-2"  src ="~/img/@c.productImg" \/>
              <div class="card-body">
              <h3 class="card-title"><i>@c.productName</i></h3>
              <p class="card-text"> Price : @c.price</p>
              </div>
            </div>
            
               
            }
        </div>
    }

    </div>
<h2 class="col-md-4 mt-4 mb-4 ">Style 2</h2>

    <div class="container">
        <div class="row">
            @foreach(var c in names)
       {
            <div class="col-md-4">
                <div class="card-content">
                    <div class="card-img p-2">
                        <img src="~/img/@c.productImg" alt="">
                        <span><h4>Discount</h4></span>
                    </div>
                    <div class="card-desc">
                        <h3>@c.productName</h3>
                        <p>Price : @c.price</p>
                            <a href="#" class="btn-card">Details</a>   
                    </div>
                </div>
            </div>
           
          }
        </div>
    </div>